# Example Streamlit secrets.toml file

path = 'd:\data_sources\TCS\tcs.csv'

env = 'SERVER'

[LOCAL]
HOST ='SHRABANI'
DATABASE ='demo'
USER ='python_user'
PWD = 'test'

[SERVER]
HOST='sqlserver01.bharatgai.com, 15433'
DATABASE = 'demo'
USER = 'sa'
PWD = 'YourStrong!Passw0rd'


[api_keys]
openai = "your_openai_api_key"
another_service = "your_other_api_key"